### ISSUE TITLE
Lacking documentation

### ISSUE THREAD

**Issue by FranklinHu1** [ktjlee/problems#2]
Hi,

I was recently browsing your code and while it all looks very compact and clean, would it be possible to add some documentation? Maintainable code is well-documented, so docstrings would be much appreciated.

Thanks!

**Comment by ktjlee** [comment]
Frank!

So nice to hear from you. You have a good point there about including some documentation. At first, I didn't see the value of documentation when I didn't expect someone to really look through the repo. As I gain more traction with loyal followers, like you, I am more motivated to include README's. Ciao~
